version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - contacts-mysql_data:/var/lib/mysql
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=contacts_app

  springboot:
    image: contacts-springboot-app
    container_name: contacts-springboot-app-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  react:
    image: contacts-react-app
    container_name: contacts-react-app-container
    ports:
      - "80:80"
    depends_on:
      - springboot
    networks:
      - app-network

volumes:
  contacts-mysql_data:

networks:
  app-network:
